server:
  port: 9005
spring:
  application:
    name: client-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
zuul:
  routes:
    api-a:
      path: /producer/**
      serviceId: spring-cloud-producer
